<?php

/**
 * authFacebook
 * Facebook authentication plugin.
 *
 * @uses authCommon
 * @uses authModel
 * @package Auth
 * @version 0.1.2
 * @copyright Copyright (c) 2010 Serenity Media
 * @author  Victor Nițu
 * @license AGPLv3 {@link http://www.gnu.org/licenses/agpl-3.0.html}
 */
class authFacebook extends authCommon implements authModel {

    public function  __construct() {
        //
    }
}
?>
